# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: molnmiljo
# "service" is the name of this project. This will also be added to your AWS resource names.
service: just-post-it-backend

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:*
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "*"
  httpApi:
    cors: true

functions:
  GetNotes:
    handler: functions/GetNotes/handler.hello
    events:
      - httpApi:
          path: /notes
          method: get
  PostNote:
    handler: functions/PostNote/handler.hello
    events:
      - httpApi:
          path: /notes
          method: post
  GetNote:
    handler: functions/GetNote/handler.hello
    events:
      - httpApi:
          path: /notes/{id}
          method: get
  PutNote:
    handler: functions/PutNote/handler.hello
    events:
      - httpApi:
          path: /notes/{id}
          method: put
  Delete:
    handler: functions/DeleteNote/handler.hello
    events:
      - httpApi:
          path: /notes/{id}
          method: delete
  GetUserNotes:
    handler: functions/GetUserNotes/handler.hello
    events:
      - httpApi:
          path: /notes/users/{user}
          method: get
  

resources:
  Resources:
    FileManager:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: NoteManager
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST